version: '3'
services:
  nakashima:
    build: .
    shm_size: '32gb'
    volumes:
      - /home/otake/LAV-CVPR21:/root/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    stdin_open: true
